# rochel = User.create(username: "rochel", password: "rochel227")
# kat = User.create(username: "kat", password: "kat11")

french = Language.create(name: "french")
spanish = Language.create(name: "spanish")
hebrew = Language.create(name: "hebrew")
greek = Language.create(name: "greek")

si = Word.create(name: "sí", english_translation: "yes", language_id: spanish.id)
hola = Word.create(name: "hola", english_translation: "hello", language_id: spanish.id)
bonita = Word.create(name: "bonita", english_translation: "pretty", language_id: spanish.id)
hombre = Word.create(name: "hombre", english_translation: "man", language_id: spanish.id)
nadar = Word.create(name: "nadar", english_translation: "to swim", language_id: spanish.id)
bailar = Word.create(name: "bailar", english_translation: "to dance", language_id: spanish.id)
cantar = Word.create(name: "cantar", english_translation: "to sing", language_id: spanish.id)
contento = Word.create(name: "contento", english_translation: "happy", language_id: spanish.id)
computadora = Word.create(name: "computadora", english_translation: "computer", language_id: spanish.id)
sombrero = Word.create(name: "sombrero", english_translation: "hat", language_id: spanish.id)
agua = Word.create(name: "agua", english_translation: "water", language_id: spanish.id)
silla = Word.create(name: "silla", english_translation: "chair", language_id: spanish.id)
papel = Word.create(name: "papel", english_translation: "paper", language_id: spanish.id)
lapiz = Word.create(name: "lápiz", english_translation: "pencil", language_id: spanish.id)
plato = Word.create(name: "plato", english_translation: "plate", language_id: spanish.id)

cama = Word.create(name: "cama", english_translation: "bed", language_id: spanish.id)

silla = Word.create(name: "silla", english_translation: "chair", language_id: spanish.id)
papel = Word.create(name: "papel", english_translation: "paper", language_id: spanish.id)
lapiz = Word.create(name: "lápiz", english_translation: "pencil", language_id: spanish.id)
plato = Word.create(name: "plato", english_translation: "plate", language_id: spanish.id)

ken = Word.create(name: "כן", english_translation: "yes", language_id: hebrew.id)
shalom = Word.create(name: "שלום", english_translation: "hello", language_id: hebrew.id)
yafeh = Word.create(name: "יפה", english_translation: "pretty", language_id: hebrew.id)

# rochel_yafeh = LearnedWord.create(user_id: rochel.id, word_id: yafeh.id)
# rochel_shalom = LearnedWord.create(user_id: rochel.id, word_id: shalom.id)
# rochel_si = LearnedWord.create(user_id: rochel.id, word_id: si.id)
#
# kat_hola = LearnedWord.create(user_id: kat.id, word_id: hola.id)
# kat_si = LearnedWord.create(user_id: kat.id, word_id: si.id)
#
#
# rochel_hebrew_points = Point.create(total: 2, user_id: rochel.id, language_id: hebrew.id)
# rochel_spanish_points = Point.create(total: 1, user_id: rochel.id, language_id: spanish.id)
# kat_spanish_points = Point.create(total: 2, user_id: kat.id, language_id: spanish.id)


yiasu = Word.create(name: 'Χαίρετε', english_translation: 'hello', language_id: greek.id)
pothilato = Word.create(name: 'ποδήλατο', english_translation: 'bike', language_id: greek.id)
fagito = Word.create(name: 'φαγητό', english_translation: 'food', language_id: greek.id)
kalo = Word.create(name: 'καλό', english_translation: 'good', language_id: greek.id)
xaroumeni = Word.create(name: 'χαρούμενη', english_translation: 'happy', language_id: greek.id)
statheros = Word.create(name: 'σταθερός', english_translation: 'constant', language_id: greek.id)
boithi = Word.create(name: 'βοηθοι', english_translation: 'help', language_id: greek.id)
poto = Word.create(name: 'ποτό', english_translation: 'drink', language_id: greek.id)
frouta = Word.create(name: 'φρούτα', english_translation: 'fruit', language_id: greek.id)
zoo = Word.create(name: 'ζώο', english_translation: 'animal', language_id: greek.id)
agapi = Word.create(name: 'αγάπη', english_translation: 'love', language_id: greek.id)
filos = Word.create(name: 'φίλος', english_translation: 'friend', language_id: greek.id)
mitera = Word.create(name: 'μητέρα', english_translation: 'mother', language_id: greek.id)
patera = Word.create(name: 'πατέρας', english_translation: 'father', language_id: greek.id)
fovero = Word.create(name: 'φοβερο', english_translation: 'fruit', language_id: greek.id)

bonjour = Word.create(name: 'Bonjour', english_translation: 'hello', language_id: french.id)
bicyclette = Word.create(name: 'bicyclette', english_translation: 'bike', language_id: french.id)
aliments = Word.create(name: 'aliments', english_translation: 'food', language_id: french.id)
bien = Word.create(name: 'bien', english_translation: 'good', language_id: french.id)
content = Word.create(name: 'content', english_translation: 'happy', language_id: french.id)
stable = Word.create(name: 'stable', english_translation: 'steady', language_id: french.id)
aide = Word.create(name: 'aide', english_translation: 'help', language_id: french.id)
boisson = Word.create(name: 'boisson', english_translation: 'drink', language_id: french.id)
fruit = Word.create(name: 'fruit', english_translation: 'fruit', language_id: french.id)
animal = Word.create(name: 'animal', english_translation: 'animal', language_id: french.id)
amour = Word.create(name: 'amour', english_translation: 'love', language_id: french.id)
ami = Word.create(name: 'ami', english_translation: 'friend', language_id: french.id)
mere = Word.create(name: 'mere', english_translation: 'mother', language_id: french.id)
pere = Word.create(name: 'pere', english_translation: 'father', language_id: french.id)
incroyable = Word.create(name: 'incroyable', english_translation: 'fruit', language_id: french.id)
